///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CoralReefTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AlimSiparisi recording.
    /// </summary>
    [TestModule("628c2f76-0320-4d0d-9750-5eb26cbf72f1", ModuleType.Recording, 1)]
    public partial class AlimSiparisi : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CoralReefTestRepository repository.
        /// </summary>
        public static CoralReefTestRepository repo = CoralReefTestRepository.Instance;

        static AlimSiparisi instance = new AlimSiparisi();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AlimSiparisi()
        {
            varAlimSiparisiFisNo = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AlimSiparisi Instance
        {
            get { return instance; }
        }

#region Variables

        string _varAlimSiparisiFisNo;

        /// <summary>
        /// Gets or sets the value of variable varAlimSiparisiFisNo.
        /// </summary>
        [TestVariable("dedd0a81-c58b-4292-9293-939417f9273f")]
        public string varAlimSiparisiFisNo
        {
            get { return _varAlimSiparisiFisNo; }
            set { _varAlimSiparisiFisNo = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CoralReef1.Yeni' at UpperCenter.", repo.CoralReef1.YeniInfo, new RecordItemIndex(0));
            repo.CoralReef1.Yeni.Click(Location.UpperCenter);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'ControlText' from item 'CoralReef1.AlimSiparisiFisNo' and assigning its value to variable 'varAlimSiparisiFisNo'.", repo.CoralReef1.AlimSiparisiFisNoInfo, new RecordItemIndex(1));
            varAlimSiparisiFisNo = repo.CoralReef1.AlimSiparisiFisNo.Element.GetAttributeValueText("ControlText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", varAlimSiparisiFisNo, new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'BEL01' with focus on 'CoralReef1.BelgeNo'.", repo.CoralReef1.BelgeNoInfo, new RecordItemIndex(3));
            repo.CoralReef1.BelgeNo.PressKeys("BEL01");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CoralReef1.CariHesap' at Center.", repo.CoralReef1.CariHesapInfo, new RecordItemIndex(4));
            repo.CoralReef1.CariHesap.Click();
            Delay.Milliseconds(0);
            
            clickToTableCellWithSearchValue(repo.CoralReef.TableInfo, "CH Kodu", "2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'İşlem Dövizi' with focus on 'CoralReef1.KullanilacakParaBirimiSatirlar'.", repo.CoralReef1.KullanilacakParaBirimiSatirlarInfo, new RecordItemIndex(6));
            repo.CoralReef1.KullanilacakParaBirimiSatirlar.PressKeys("İşlem Dövizi");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ABD Doları' with focus on 'CoralReef1.IslemDovizTuru'.", repo.CoralReef1.IslemDovizTuruInfo, new RecordItemIndex(7));
            repo.CoralReef1.IslemDovizTuru.PressKeys("ABD Doları");
            Delay.Milliseconds(0);
            
            // Yeni Kayıt
            Report.Log(ReportLevel.Info, "Section", "Yeni Kayıt", new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CoralReef1.Yeni1' at Center.", repo.CoralReef1.Yeni1Info, new RecordItemIndex(9));
            repo.CoralReef1.Yeni1.Click();
            Delay.Milliseconds(0);
            
            clickToTableCell(repo.CoralReef1.TableInfo, "Stok Kartı", ValueConverter.ArgumentFromString<int>("rowIndex", "1"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'HAMMADDE03aaa' with focus on 'CoralReef.StokKartiSearchBox'.", repo.CoralReef.StokKartiSearchBoxInfo, new RecordItemIndex(11));
            repo.CoralReef.StokKartiSearchBox.PressKeys("HAMMADDE03aaa");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CoralReef.StokKartiSearchButton' at Center.", repo.CoralReef.StokKartiSearchButtonInfo, new RecordItemIndex(12));
            repo.CoralReef.StokKartiSearchButton.Click();
            Delay.Milliseconds(0);
            
            clickToTableCellWithSearchValue(repo.CoralReef.TableInfo, "Adı", "HAMMADDE03aaa");
            Delay.Milliseconds(0);
            
            writeToTableCell(repo.CoralReef1.TableInfo, "Miktar", ValueConverter.ArgumentFromString<int>("rowIndex", "1"), "100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CoralReef1.KaydetVeKapat' at Center.", repo.CoralReef1.KaydetVeKapatInfo, new RecordItemIndex(15));
            repo.CoralReef1.KaydetVeKapat.Click();
            Delay.Milliseconds(0);
            
            // Yeni Kaydı Filtrele ve Onayla
            Report.Log(ReportLevel.Info, "Section", "Yeni Kaydı Filtrele ve Onayla", new RecordItemIndex(16));
            
            writeToTableCell(repo.MainForm.FilterTableInfo, "Fiş No", ValueConverter.ArgumentFromString<int>("rowIndex", "1"), varAlimSiparisiFisNo);
            Delay.Milliseconds(0);
            
            clickToTableCell(repo.MainForm.FilterTableInfo, "Seç", ValueConverter.ArgumentFromString<int>("rowIndex", "2"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Onayla' at Center.", repo.MainForm.OnaylaInfo, new RecordItemIndex(19));
            repo.MainForm.Onayla.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'CoralReef1.OnayıİptalEt'.", repo.CoralReef1.OnayıİptalEtInfo, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.CoralReef1.OnayıİptalEtInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'MainForm.Onayla'.", repo.MainForm.OnaylaInfo, new RecordItemIndex(21));
            Validate.AttributeEqual(repo.MainForm.OnaylaInfo, "Enabled", "False");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
