///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CoralReefTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CoralReefTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("42dfcedf-318e-46e3-9953-ed41d0550cbe")]
    public partial class CoralReefTestRepository : RepoGenBaseFolder
    {
        static CoralReefTestRepository instance = new CoralReefTestRepository();
        CoralReefTestRepositoryFolders.LoginScreenAppFolder _loginscreen;
        CoralReefTestRepositoryFolders.MainFormAppFolder _mainform;
        CoralReefTestRepositoryFolders.LoginScreen1AppFolder _loginscreen1;
        CoralReefTestRepositoryFolders.SatisSiparisiAppFolder _satissiparisi;
        CoralReefTestRepositoryFolders.SatisSiparisiDetaylariAppFolder _satissiparisidetaylari;
        CoralReefTestRepositoryFolders.CoralReefAppFolder _coralreef;
        CoralReefTestRepositoryFolders.CoralReef1AppFolder _coralreef1;
        CoralReefTestRepositoryFolders.PopupFormAppFolder _popupform;

        /// <summary>
        /// Gets the singleton class instance representing the CoralReefTestRepository element repository.
        /// </summary>
        [RepositoryFolder("42dfcedf-318e-46e3-9953-ed41d0550cbe")]
        public static CoralReefTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CoralReefTestRepository() 
            : base("CoralReefTestRepository", "/", null, 0, false, "42dfcedf-318e-46e3-9953-ed41d0550cbe", ".\\RepositoryImages\\CoralReefTestRepository42dfcedf.rximgres")
        {
            _loginscreen = new CoralReefTestRepositoryFolders.LoginScreenAppFolder(this);
            _mainform = new CoralReefTestRepositoryFolders.MainFormAppFolder(this);
            _loginscreen1 = new CoralReefTestRepositoryFolders.LoginScreen1AppFolder(this);
            _satissiparisi = new CoralReefTestRepositoryFolders.SatisSiparisiAppFolder(this);
            _satissiparisidetaylari = new CoralReefTestRepositoryFolders.SatisSiparisiDetaylariAppFolder(this);
            _coralreef = new CoralReefTestRepositoryFolders.CoralReefAppFolder(this);
            _coralreef1 = new CoralReefTestRepositoryFolders.CoralReef1AppFolder(this);
            _popupform = new CoralReefTestRepositoryFolders.PopupFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("42dfcedf-318e-46e3-9953-ed41d0550cbe")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The LoginScreen folder.
        /// </summary>
        [RepositoryFolder("81774e3c-2f98-4934-8c68-06454a88101e")]
        public virtual CoralReefTestRepositoryFolders.LoginScreenAppFolder LoginScreen
        {
            get { return _loginscreen; }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("2a82f78e-3f4b-4cff-8380-63085bb54028")]
        public virtual CoralReefTestRepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The LoginScreen1 folder.
        /// </summary>
        [RepositoryFolder("82532593-1937-4b66-8f5d-3e93b36d984b")]
        public virtual CoralReefTestRepositoryFolders.LoginScreen1AppFolder LoginScreen1
        {
            get { return _loginscreen1; }
        }

        /// <summary>
        /// The SatisSiparisi folder.
        /// </summary>
        [RepositoryFolder("9fcec3df-783c-47d8-8605-71c6426648ca")]
        public virtual CoralReefTestRepositoryFolders.SatisSiparisiAppFolder SatisSiparisi
        {
            get { return _satissiparisi; }
        }

        /// <summary>
        /// The SatisSiparisiDetaylari folder.
        /// </summary>
        [RepositoryFolder("c3ac9da6-b7f2-4446-8524-b7636ff51c2f")]
        public virtual CoralReefTestRepositoryFolders.SatisSiparisiDetaylariAppFolder SatisSiparisiDetaylari
        {
            get { return _satissiparisidetaylari; }
        }

        /// <summary>
        /// The CoralReef folder.
        /// </summary>
        [RepositoryFolder("94b92571-c35d-4600-b63e-75b1318acc33")]
        public virtual CoralReefTestRepositoryFolders.CoralReefAppFolder CoralReef
        {
            get { return _coralreef; }
        }

        /// <summary>
        /// The CoralReef1 folder.
        /// </summary>
        [RepositoryFolder("d80cb17a-75d5-4f3b-882e-5a935cc25e4a")]
        public virtual CoralReefTestRepositoryFolders.CoralReef1AppFolder CoralReef1
        {
            get { return _coralreef1; }
        }

        /// <summary>
        /// The PopupForm folder.
        /// </summary>
        [RepositoryFolder("838e4a8a-d1b6-4c7e-bd7d-9caae382a530")]
        public virtual CoralReefTestRepositoryFolders.PopupFormAppFolder PopupForm
        {
            get { return _popupform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CoralReefTestRepositoryFolders
    {
        /// <summary>
        /// The LoginScreenAppFolder folder.
        /// </summary>
        [RepositoryFolder("81774e3c-2f98-4934-8c68-06454a88101e")]
        public partial class LoginScreenAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtusernameInfo;
            RepoItemInfo _textmaskbox1Info;
            RepoItemInfo _sİstemebağlanInfo;

            /// <summary>
            /// Creates a new LoginScreen  folder.
            /// </summary>
            public LoginScreenAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginScreen", "/form[@controlname='LoginScreen']", parentFolder, 120000, null, true, "81774e3c-2f98-4934-8c68-06454a88101e", "")
            {
                _txtusernameInfo = new RepoItemInfo(this, "txtUsername", "?/?/text[@controlname='_maskBox']", 120000, null, "81466fa2-3c53-44dd-a997-897325808469");
                _textmaskbox1Info = new RepoItemInfo(this, "TextMaskBox1", "element[@controlname='PasswordEdit']/text[@controlname='_maskBox']", 120000, null, "8cb7b1e6-82b3-43ad-ad7c-f4d11fef3dc7");
                _sİstemebağlanInfo = new RepoItemInfo(this, "SİSTEMEBAĞLAN", "?/?/button[@accessiblename='SİSTEME BAĞLAN']", 120000, null, "3e7e98f2-9d77-4d35-be45-b56a0ff43237");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("81774e3c-2f98-4934-8c68-06454a88101e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("81774e3c-2f98-4934-8c68-06454a88101e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtUsername item.
            /// </summary>
            [RepositoryItem("81466fa2-3c53-44dd-a997-897325808469")]
            public virtual Ranorex.Text txtUsername
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtUsername item info.
            /// </summary>
            [RepositoryItemInfo("81466fa2-3c53-44dd-a997-897325808469")]
            public virtual RepoItemInfo txtUsernameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }

            /// <summary>
            /// The TextMaskBox1 item.
            /// </summary>
            [RepositoryItem("8cb7b1e6-82b3-43ad-ad7c-f4d11fef3dc7")]
            public virtual Ranorex.Text TextMaskBox1
            {
                get
                {
                    return _textmaskbox1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextMaskBox1 item info.
            /// </summary>
            [RepositoryItemInfo("8cb7b1e6-82b3-43ad-ad7c-f4d11fef3dc7")]
            public virtual RepoItemInfo TextMaskBox1Info
            {
                get
                {
                    return _textmaskbox1Info;
                }
            }

            /// <summary>
            /// The SİSTEMEBAĞLAN item.
            /// </summary>
            [RepositoryItem("3e7e98f2-9d77-4d35-be45-b56a0ff43237")]
            public virtual Ranorex.Button SİSTEMEBAĞLAN
            {
                get
                {
                    return _sİstemebağlanInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SİSTEMEBAĞLAN item info.
            /// </summary>
            [RepositoryItemInfo("3e7e98f2-9d77-4d35-be45-b56a0ff43237")]
            public virtual RepoItemInfo SİSTEMEBAĞLANInfo
            {
                get
                {
                    return _sİstemebağlanInfo;
                }
            }
        }

        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("2a82f78e-3f4b-4cff-8380-63085bb54028")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            CoralReefTestRepositoryFolders.DockPanelNavigationFolder _dockpanelnavigation;
            RepoItemInfo _filtertableInfo;
            RepoItemInfo _onaylaInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 120000, null, true, "2a82f78e-3f4b-4cff-8380-63085bb54028", "")
            {
                _dockpanelnavigation = new CoralReefTestRepositoryFolders.DockPanelNavigationFolder(this);
                _filtertableInfo = new RepoItemInfo(this, "FilterTable", "container[@controlname='viewSitePanel']/?/?/table[@accessiblerole='Table']", 30000, null, "f9ac4355-5d3b-49ca-bb22-8e323ef18578");
                _onaylaInfo = new RepoItemInfo(this, "Onayla", "?/?/container[@accessiblename='Lower Ribbon']/?/?/toolbar[@accessiblename='Default']/button[121]", 30000, null, "ed90f603-f4e0-4ea7-a66b-5709571f7bee");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2a82f78e-3f4b-4cff-8380-63085bb54028")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2a82f78e-3f4b-4cff-8380-63085bb54028")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FilterTable item.
            /// </summary>
            [RepositoryItem("f9ac4355-5d3b-49ca-bb22-8e323ef18578")]
            public virtual Ranorex.Table FilterTable
            {
                get
                {
                    return _filtertableInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The FilterTable item info.
            /// </summary>
            [RepositoryItemInfo("f9ac4355-5d3b-49ca-bb22-8e323ef18578")]
            public virtual RepoItemInfo FilterTableInfo
            {
                get
                {
                    return _filtertableInfo;
                }
            }

            /// <summary>
            /// The Onayla item.
            /// </summary>
            [RepositoryItem("ed90f603-f4e0-4ea7-a66b-5709571f7bee")]
            public virtual Ranorex.Button Onayla
            {
                get
                {
                    return _onaylaInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Onayla item info.
            /// </summary>
            [RepositoryItemInfo("ed90f603-f4e0-4ea7-a66b-5709571f7bee")]
            public virtual RepoItemInfo OnaylaInfo
            {
                get
                {
                    return _onaylaInfo;
                }
            }

            /// <summary>
            /// The DockPanelNavigation folder.
            /// </summary>
            [RepositoryFolder("5579cb27-69ed-4e7a-8fd8-36343e059f51")]
            public virtual CoralReefTestRepositoryFolders.DockPanelNavigationFolder DockPanelNavigation
            {
                get { return _dockpanelnavigation; }
            }
        }

        /// <summary>
        /// The DockPanelNavigationFolder folder.
        /// </summary>
        [RepositoryFolder("5579cb27-69ed-4e7a-8fd8-36343e059f51")]
        public partial class DockPanelNavigationFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonbulInfo;
            RepoItemInfo _txtislemaraInfo;
            RepoItemInfo _captionrow0Info;
            RepoItemInfo _ilkislemInfo;

            /// <summary>
            /// Creates a new DockPanelNavigation  folder.
            /// </summary>
            public DockPanelNavigationFolder(RepoGenBaseFolder parentFolder) :
                    base("DockPanelNavigation", "container[@controlname='dockPanelNavigation']", parentFolder, 30000, null, false, "5579cb27-69ed-4e7a-8fd8-36343e059f51", "")
            {
                _buttonbulInfo = new RepoItemInfo(this, "ButtonBul", ".//container[@controlname='FindControlCore']/?/?/element[@controlname='btFind']/button[@accessiblename='Bul']", 30000, null, "a098d5ad-e57e-4f8f-b9b3-5d09a1c2ec5d");
                _txtislemaraInfo = new RepoItemInfo(this, "txtIslemAra", ".//container[@controlname='FindControlCore']/container[@controlname='layoutControl1']/?/?/text[@controltypename='TextBoxMaskBox']", 30000, null, "f983b163-9701-4cdb-8f02-52bd821db7de");
                _captionrow0Info = new RepoItemInfo(this, "CaptionRow0", ".//tree[@accessiblerole='Outline']/?/?/treeitem[@accessiblename='Düğüm0']/cell[@accessiblename='Caption row 0']", 30000, null, "22fcab53-f4e2-4667-a2d0-1399f0c88a6e");
                _ilkislemInfo = new RepoItemInfo(this, "IlkIslem", "container[@controlname='dockPanelNavigation_Container']//tree[@accessiblerole='Outline']/?/?/treeitem[@accessiblename='Düğüm0']", 30000, null, "03addd18-ea83-46b3-a88e-12d30ef8ef67");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5579cb27-69ed-4e7a-8fd8-36343e059f51")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5579cb27-69ed-4e7a-8fd8-36343e059f51")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonBul item.
            /// </summary>
            [RepositoryItem("a098d5ad-e57e-4f8f-b9b3-5d09a1c2ec5d")]
            public virtual Ranorex.Button ButtonBul
            {
                get
                {
                    return _buttonbulInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonBul item info.
            /// </summary>
            [RepositoryItemInfo("a098d5ad-e57e-4f8f-b9b3-5d09a1c2ec5d")]
            public virtual RepoItemInfo ButtonBulInfo
            {
                get
                {
                    return _buttonbulInfo;
                }
            }

            /// <summary>
            /// The txtIslemAra item.
            /// </summary>
            [RepositoryItem("f983b163-9701-4cdb-8f02-52bd821db7de")]
            public virtual Ranorex.Text txtIslemAra
            {
                get
                {
                    return _txtislemaraInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtIslemAra item info.
            /// </summary>
            [RepositoryItemInfo("f983b163-9701-4cdb-8f02-52bd821db7de")]
            public virtual RepoItemInfo txtIslemAraInfo
            {
                get
                {
                    return _txtislemaraInfo;
                }
            }

            /// <summary>
            /// The CaptionRow0 item.
            /// </summary>
            [RepositoryItem("22fcab53-f4e2-4667-a2d0-1399f0c88a6e")]
            public virtual Ranorex.Cell CaptionRow0
            {
                get
                {
                    return _captionrow0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CaptionRow0 item info.
            /// </summary>
            [RepositoryItemInfo("22fcab53-f4e2-4667-a2d0-1399f0c88a6e")]
            public virtual RepoItemInfo CaptionRow0Info
            {
                get
                {
                    return _captionrow0Info;
                }
            }

            /// <summary>
            /// The IlkIslem item.
            /// </summary>
            [RepositoryItem("03addd18-ea83-46b3-a88e-12d30ef8ef67")]
            public virtual Ranorex.TreeItem IlkIslem
            {
                get
                {
                    return _ilkislemInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The IlkIslem item info.
            /// </summary>
            [RepositoryItemInfo("03addd18-ea83-46b3-a88e-12d30ef8ef67")]
            public virtual RepoItemInfo IlkIslemInfo
            {
                get
                {
                    return _ilkislemInfo;
                }
            }
        }

        /// <summary>
        /// The LoginScreen1AppFolder folder.
        /// </summary>
        [RepositoryFolder("82532593-1937-4b66-8f5d-3e93b36d984b")]
        public partial class LoginScreen1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textmaskboxInfo;

            /// <summary>
            /// Creates a new LoginScreen1  folder.
            /// </summary>
            public LoginScreen1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginScreen1", "/form[@controltypename='LoginScreen']", parentFolder, 120000, null, true, "82532593-1937-4b66-8f5d-3e93b36d984b", "")
            {
                _textmaskboxInfo = new RepoItemInfo(this, "TextMaskBox", "?/?/text[1]", 30000, null, "bfc64aa4-fa53-4f54-ba88-0a3a6fe64ee8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("82532593-1937-4b66-8f5d-3e93b36d984b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("82532593-1937-4b66-8f5d-3e93b36d984b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TextMaskBox item.
            /// </summary>
            [RepositoryItem("bfc64aa4-fa53-4f54-ba88-0a3a6fe64ee8")]
            public virtual Ranorex.Text TextMaskBox
            {
                get
                {
                    return _textmaskboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextMaskBox item info.
            /// </summary>
            [RepositoryItemInfo("bfc64aa4-fa53-4f54-ba88-0a3a6fe64ee8")]
            public virtual RepoItemInfo TextMaskBoxInfo
            {
                get
                {
                    return _textmaskboxInfo;
                }
            }
        }

        /// <summary>
        /// The SatisSiparisiAppFolder folder.
        /// </summary>
        [RepositoryFolder("9fcec3df-783c-47d8-8605-71c6426648ca")]
        public partial class SatisSiparisiAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _yeniInfo;

            /// <summary>
            /// Creates a new SatisSiparisi  folder.
            /// </summary>
            public SatisSiparisiAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SatisSiparisi", "/form[@controltext='Satış Siparişi - CoralReef Üretim Takip']", parentFolder, 30000, null, true, "9fcec3df-783c-47d8-8605-71c6426648ca", "")
            {
                _yeniInfo = new RepoItemInfo(this, "Yeni", "?/?/container[@accessiblename='Lower Ribbon']/?/?/toolbar[@accessiblename='Objects Creation']/button[@accessiblename='Yeni']", 30000, null, "fafcd38b-a28c-4b50-86d2-48af2a54de4e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9fcec3df-783c-47d8-8605-71c6426648ca")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9fcec3df-783c-47d8-8605-71c6426648ca")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Yeni item.
            /// </summary>
            [RepositoryItem("fafcd38b-a28c-4b50-86d2-48af2a54de4e")]
            public virtual Ranorex.Button Yeni
            {
                get
                {
                    return _yeniInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Yeni item info.
            /// </summary>
            [RepositoryItemInfo("fafcd38b-a28c-4b50-86d2-48af2a54de4e")]
            public virtual RepoItemInfo YeniInfo
            {
                get
                {
                    return _yeniInfo;
                }
            }
        }

        /// <summary>
        /// The SatisSiparisiDetaylariAppFolder folder.
        /// </summary>
        [RepositoryFolder("c3ac9da6-b7f2-4446-8524-b7636ff51c2f")]
        public partial class SatisSiparisiDetaylariAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fisnoInfo;
            RepoItemInfo _carihesapInfo;
            RepoItemInfo _yeniInfo;
            RepoItemInfo _tableInfo;
            RepoItemInfo _fistarihiInfo;
            RepoItemInfo _siparisdurumuInfo;
            RepoItemInfo _uretimemriolusturInfo;
            RepoItemInfo _kapatInfo;

            /// <summary>
            /// Creates a new SatisSiparisiDetaylari  folder.
            /// </summary>
            public SatisSiparisiDetaylariAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SatisSiparisiDetaylari", "/form[@controltext='Satış Siparişi']", parentFolder, 30000, null, true, "c3ac9da6-b7f2-4446-8524-b7636ff51c2f", "")
            {
                _fisnoInfo = new RepoItemInfo(this, "FisNo", "container[@controlname='viewSitePanel']/?/?/element[@controlname='Number(5)']", 30000, null, "8c9bbc66-9db6-4639-9b85-c172a4613a37");
                _carihesapInfo = new RepoItemInfo(this, "CariHesap", "container[@controlname='viewSitePanel']/?/?/element[@controlname='ClientCard(7)']", 30000, null, "8a863eae-b899-481e-99d6-25433cb29f4a");
                _yeniInfo = new RepoItemInfo(this, "Yeni", "container[@controlname='viewSitePanel']/?/?/container[@controlname='Lines(20)']//toolbar[@accessiblename='Araç çubuğu']/button[@accessiblename='Yeni']", 30000, null, "d5f60be8-6d64-4e9f-a97d-bc2649f2fd0a");
                _tableInfo = new RepoItemInfo(this, "Table", "container[@controlname='viewSitePanel']/?/?/container[@controlname='Lines(20)']//table[@accessiblerole='Table'][2]", 30000, null, "6912de24-00c8-4d39-8954-bf4c45bfbfd8");
                _fistarihiInfo = new RepoItemInfo(this, "FisTarihi", "container[@controlname='viewSitePanel']/?/?/element[@controlname='Date(6)']", 30000, null, "07d67d43-4df2-4e27-8fe9-48067aad42e2");
                _siparisdurumuInfo = new RepoItemInfo(this, "SiparisDurumu", "container[@controlname='viewSitePanel']/?/?/element[@controlname='OrderStatus(14)']", 30000, null, "26f471cc-2a5d-4c3a-a923-9f60cd09915f");
                _uretimemriolusturInfo = new RepoItemInfo(this, "UretimEmriOlustur", "?/?/container[@accessiblename='Lower Ribbon']/?/?/toolbar[@accessiblename='Görünüm']/button[@text='Üretim Emri Oluştur' and @accessiblerole='PushButton' and @accessibledescription>'Girilen ve Varsayılan Reçetesi']", 30000, null, "484c0de2-79bb-4971-a824-602387e406dd");
                _kapatInfo = new RepoItemInfo(this, "Kapat", "?/?/container[@accessiblename='Lower Ribbon']/?/?/toolbar[@accessiblename='Kapat']/button[@accessiblename='Kapat']", 30000, null, "9e5f8f94-db82-4683-917e-37a2de9dd828");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c3ac9da6-b7f2-4446-8524-b7636ff51c2f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c3ac9da6-b7f2-4446-8524-b7636ff51c2f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FisNo item.
            /// </summary>
            [RepositoryItem("8c9bbc66-9db6-4639-9b85-c172a4613a37")]
            public virtual Ranorex.Unknown FisNo
            {
                get
                {
                    return _fisnoInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The FisNo item info.
            /// </summary>
            [RepositoryItemInfo("8c9bbc66-9db6-4639-9b85-c172a4613a37")]
            public virtual RepoItemInfo FisNoInfo
            {
                get
                {
                    return _fisnoInfo;
                }
            }

            /// <summary>
            /// The CariHesap item.
            /// </summary>
            [RepositoryItem("8a863eae-b899-481e-99d6-25433cb29f4a")]
            public virtual Ranorex.Unknown CariHesap
            {
                get
                {
                    return _carihesapInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The CariHesap item info.
            /// </summary>
            [RepositoryItemInfo("8a863eae-b899-481e-99d6-25433cb29f4a")]
            public virtual RepoItemInfo CariHesapInfo
            {
                get
                {
                    return _carihesapInfo;
                }
            }

            /// <summary>
            /// The Yeni item.
            /// </summary>
            [RepositoryItem("d5f60be8-6d64-4e9f-a97d-bc2649f2fd0a")]
            public virtual Ranorex.Button Yeni
            {
                get
                {
                    return _yeniInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Yeni item info.
            /// </summary>
            [RepositoryItemInfo("d5f60be8-6d64-4e9f-a97d-bc2649f2fd0a")]
            public virtual RepoItemInfo YeniInfo
            {
                get
                {
                    return _yeniInfo;
                }
            }

            /// <summary>
            /// The Table item.
            /// </summary>
            [RepositoryItem("6912de24-00c8-4d39-8954-bf4c45bfbfd8")]
            public virtual Ranorex.Table Table
            {
                get
                {
                    return _tableInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Table item info.
            /// </summary>
            [RepositoryItemInfo("6912de24-00c8-4d39-8954-bf4c45bfbfd8")]
            public virtual RepoItemInfo TableInfo
            {
                get
                {
                    return _tableInfo;
                }
            }

            /// <summary>
            /// The FisTarihi item.
            /// </summary>
            [RepositoryItem("07d67d43-4df2-4e27-8fe9-48067aad42e2")]
            public virtual Ranorex.Unknown FisTarihi
            {
                get
                {
                    return _fistarihiInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The FisTarihi item info.
            /// </summary>
            [RepositoryItemInfo("07d67d43-4df2-4e27-8fe9-48067aad42e2")]
            public virtual RepoItemInfo FisTarihiInfo
            {
                get
                {
                    return _fistarihiInfo;
                }
            }

            /// <summary>
            /// The SiparisDurumu item.
            /// </summary>
            [RepositoryItem("26f471cc-2a5d-4c3a-a923-9f60cd09915f")]
            public virtual Ranorex.Unknown SiparisDurumu
            {
                get
                {
                    return _siparisdurumuInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SiparisDurumu item info.
            /// </summary>
            [RepositoryItemInfo("26f471cc-2a5d-4c3a-a923-9f60cd09915f")]
            public virtual RepoItemInfo SiparisDurumuInfo
            {
                get
                {
                    return _siparisdurumuInfo;
                }
            }

            /// <summary>
            /// The UretimEmriOlustur item.
            /// </summary>
            [RepositoryItem("484c0de2-79bb-4971-a824-602387e406dd")]
            public virtual Ranorex.Button UretimEmriOlustur
            {
                get
                {
                    return _uretimemriolusturInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UretimEmriOlustur item info.
            /// </summary>
            [RepositoryItemInfo("484c0de2-79bb-4971-a824-602387e406dd")]
            public virtual RepoItemInfo UretimEmriOlusturInfo
            {
                get
                {
                    return _uretimemriolusturInfo;
                }
            }

            /// <summary>
            /// The Kapat item.
            /// </summary>
            [RepositoryItem("9e5f8f94-db82-4683-917e-37a2de9dd828")]
            public virtual Ranorex.Button Kapat
            {
                get
                {
                    return _kapatInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Kapat item info.
            /// </summary>
            [RepositoryItemInfo("9e5f8f94-db82-4683-917e-37a2de9dd828")]
            public virtual RepoItemInfo KapatInfo
            {
                get
                {
                    return _kapatInfo;
                }
            }
        }

        /// <summary>
        /// The CoralReefAppFolder folder.
        /// </summary>
        [RepositoryFolder("94b92571-c35d-4600-b63e-75b1318acc33")]
        public partial class CoralReefAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tableInfo;
            RepoItemInfo _stokkartisearchboxInfo;
            RepoItemInfo _stokkartisearchbuttonInfo;

            /// <summary>
            /// Creates a new CoralReef  folder.
            /// </summary>
            public CoralReefAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CoralReef", "/form[@title='']", parentFolder, 30000, null, true, "94b92571-c35d-4600-b63e-75b1318acc33", "")
            {
                _tableInfo = new RepoItemInfo(this, "Table", "?/?/container[@controlname='LookupControlTemplate']/?/?/container[@controlname='viewSitePanel']/?/?/table[@accessiblerole='Table']", 30000, null, "a5942122-5346-4d39-8ac4-1732a54018dd");
                _stokkartisearchboxInfo = new RepoItemInfo(this, "StokKartiSearchBox", ".//container[@controlname='controlsPanel']/?/?/container[@controlname='typeAndFindPanel']/container[@controlname='searchActionContainer']/element[@tooltip='Girilen metni kayıtlarda ara']", 30000, null, "4134674a-466c-49d0-a652-1a97608d7e4f");
                _stokkartisearchbuttonInfo = new RepoItemInfo(this, "StokKartiSearchButton", ".//container[@controlname='controlsPanel']/?/?/container[@controlname='typeAndFindPanel']/container[@controlname='searchActionContainer']/element[@tooltip='Girilen metni kayıtlarda ara']/text/button[2]", 30000, null, "ec2b4ec1-1273-4857-8f70-4e5928ab8248");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("94b92571-c35d-4600-b63e-75b1318acc33")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("94b92571-c35d-4600-b63e-75b1318acc33")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Table item.
            /// </summary>
            [RepositoryItem("a5942122-5346-4d39-8ac4-1732a54018dd")]
            public virtual Ranorex.Table Table
            {
                get
                {
                    return _tableInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Table item info.
            /// </summary>
            [RepositoryItemInfo("a5942122-5346-4d39-8ac4-1732a54018dd")]
            public virtual RepoItemInfo TableInfo
            {
                get
                {
                    return _tableInfo;
                }
            }

            /// <summary>
            /// The StokKartiSearchBox item.
            /// </summary>
            [RepositoryItem("4134674a-466c-49d0-a652-1a97608d7e4f")]
            public virtual Ranorex.Unknown StokKartiSearchBox
            {
                get
                {
                    return _stokkartisearchboxInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The StokKartiSearchBox item info.
            /// </summary>
            [RepositoryItemInfo("4134674a-466c-49d0-a652-1a97608d7e4f")]
            public virtual RepoItemInfo StokKartiSearchBoxInfo
            {
                get
                {
                    return _stokkartisearchboxInfo;
                }
            }

            /// <summary>
            /// The StokKartiSearchButton item.
            /// </summary>
            [RepositoryItem("ec2b4ec1-1273-4857-8f70-4e5928ab8248")]
            public virtual Ranorex.Button StokKartiSearchButton
            {
                get
                {
                    return _stokkartisearchbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The StokKartiSearchButton item info.
            /// </summary>
            [RepositoryItemInfo("ec2b4ec1-1273-4857-8f70-4e5928ab8248")]
            public virtual RepoItemInfo StokKartiSearchButtonInfo
            {
                get
                {
                    return _stokkartisearchbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The CoralReef1AppFolder folder.
        /// </summary>
        [RepositoryFolder("d80cb17a-75d5-4f3b-882e-5a935cc25e4a")]
        public partial class CoralReef1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _kaydetInfo;
            RepoItemInfo _messagelabelInfo;
            RepoItemInfo _evetInfo;
            RepoItemInfo _buttonhayırInfo;
            RepoItemInfo _yeniInfo;
            RepoItemInfo _alimsiparisifisnoInfo;
            RepoItemInfo _belgenoInfo;
            RepoItemInfo _carihesapInfo;
            RepoItemInfo _kullanilacakparabirimisatirlarInfo;
            RepoItemInfo _islemdovizturuInfo;
            RepoItemInfo _yeni1Info;
            RepoItemInfo _tableInfo;
            RepoItemInfo _kaydetvekapatInfo;
            RepoItemInfo _onayıİptaletInfo;

            /// <summary>
            /// Creates a new CoralReef1  folder.
            /// </summary>
            public CoralReef1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("CoralReef1", "/form[@processname='CoralReef']", parentFolder, 30000, null, false, "d80cb17a-75d5-4f3b-882e-5a935cc25e4a", "")
            {
                _kaydetInfo = new RepoItemInfo(this, "Kaydet", "?/?/container[@accessiblename='Lower Ribbon']/?/?/toolbar[@accessiblename='Kaydet']/button[@accessiblekeyboardshortcut='Ctrl+S']", 30000, null, "e0e21760-495b-4d0d-8f62-aab8e1b26ae9");
                _messagelabelInfo = new RepoItemInfo(this, "MessageLabel", "text[@visible='True' and @accessiblerole='StaticText']", 30000, null, "2652e35b-b0b0-41f9-80d6-9965992c6f3c");
                _evetInfo = new RepoItemInfo(this, "Evet", "?/?/button[@accessiblename='E&vet']", 30000, null, "1db31c2a-db17-4396-baf0-0e916920c91a");
                _buttonhayırInfo = new RepoItemInfo(this, "ButtonHayır", "?/?/button[@accessiblename='&Hayır']", 30000, null, "d7dad76e-36e3-4896-bab1-0406627b0ee7");
                _yeniInfo = new RepoItemInfo(this, "Yeni", "?/?/container[@accessiblename='Lower Ribbon']/?/?/toolbar[@accessiblename='Objects Creation']/button[@accessiblename='Yeni']", 30000, null, "d46b37e0-1c37-48e0-a62e-b6d36f39a2fe");
                _alimsiparisifisnoInfo = new RepoItemInfo(this, "AlimSiparisiFisNo", "container[@controlname='viewSitePanel']/?/?/element[@controlname='Number(5)']", 30000, null, "5b3d6933-622e-495e-816f-31b3b5b33ae0");
                _belgenoInfo = new RepoItemInfo(this, "BelgeNo", "container[@controlname='viewSitePanel']/?/?/element[@controlname='DocumentCode(7)']", 30000, null, "0f0ba7e4-ec7e-45cc-a368-62d7709f3067");
                _carihesapInfo = new RepoItemInfo(this, "CariHesap", "container[@controlname='viewSitePanel']/?/?/element[@controlname='ClientCard(13)']", 30000, null, "72cb7f36-1c6f-427a-8373-cb51df793a9c");
                _kullanilacakparabirimisatirlarInfo = new RepoItemInfo(this, "KullanilacakParaBirimiSatirlar", "container[@controlname='viewSitePanel']/?/?/element[@controlname='LineCurrency(10)']", 30000, null, "2b27f1a1-b3e4-4fb0-a823-5023a332077c");
                _islemdovizturuInfo = new RepoItemInfo(this, "IslemDovizTuru", "container[@controlname='viewSitePanel']/?/?/element[@controlname='Currency(11)']", 30000, null, "3f767137-8d92-4bd9-aa6b-746034e07870");
                _yeni1Info = new RepoItemInfo(this, "Yeni1", "container[@controlname='viewSitePanel']/?/?/container[@controlname='Lines(22)']//toolbar[@accessiblename='Araç çubuğu']/button[@accessiblename='Yeni']", 30000, null, "86b39e30-9702-4a68-83a8-703e0bfb9ccc");
                _tableInfo = new RepoItemInfo(this, "Table", "container[@controlname='viewSitePanel']/?/?/container[@controlname='Lines(22)']//table[@accessiblerole='Table'][2]", 30000, null, "29f627e9-f194-40f7-ab7d-8f3bcedd921d");
                _kaydetvekapatInfo = new RepoItemInfo(this, "KaydetVeKapat", "?/?/container[@accessiblename='Lower Ribbon']/?/?/toolbar[@accessiblename='Kaydet']/button[@accessiblekeyboardshortcut='Ctrl+Return']", 30000, null, "032a3692-49d2-4009-b5ab-7a7d0f5bba4f");
                _onayıİptaletInfo = new RepoItemInfo(this, "OnayıİptalEt", "?/?/container[@accessiblename='Lower Ribbon']/?/?/toolbar[@accessiblename='Default']/button[120]", 30000, null, "b661e5df-0faf-49fc-9a8c-a3ad3a29f5c2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d80cb17a-75d5-4f3b-882e-5a935cc25e4a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d80cb17a-75d5-4f3b-882e-5a935cc25e4a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Kaydet item.
            /// </summary>
            [RepositoryItem("e0e21760-495b-4d0d-8f62-aab8e1b26ae9")]
            public virtual Ranorex.Button Kaydet
            {
                get
                {
                    return _kaydetInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Kaydet item info.
            /// </summary>
            [RepositoryItemInfo("e0e21760-495b-4d0d-8f62-aab8e1b26ae9")]
            public virtual RepoItemInfo KaydetInfo
            {
                get
                {
                    return _kaydetInfo;
                }
            }

            /// <summary>
            /// The MessageLabel item.
            /// </summary>
            [RepositoryItem("2652e35b-b0b0-41f9-80d6-9965992c6f3c")]
            public virtual Ranorex.Text MessageLabel
            {
                get
                {
                    return _messagelabelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MessageLabel item info.
            /// </summary>
            [RepositoryItemInfo("2652e35b-b0b0-41f9-80d6-9965992c6f3c")]
            public virtual RepoItemInfo MessageLabelInfo
            {
                get
                {
                    return _messagelabelInfo;
                }
            }

            /// <summary>
            /// The Evet item.
            /// </summary>
            [RepositoryItem("1db31c2a-db17-4396-baf0-0e916920c91a")]
            public virtual Ranorex.Button Evet
            {
                get
                {
                    return _evetInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Evet item info.
            /// </summary>
            [RepositoryItemInfo("1db31c2a-db17-4396-baf0-0e916920c91a")]
            public virtual RepoItemInfo EvetInfo
            {
                get
                {
                    return _evetInfo;
                }
            }

            /// <summary>
            /// The ButtonHayır item.
            /// </summary>
            [RepositoryItem("d7dad76e-36e3-4896-bab1-0406627b0ee7")]
            public virtual Ranorex.Button ButtonHayır
            {
                get
                {
                    return _buttonhayırInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonHayır item info.
            /// </summary>
            [RepositoryItemInfo("d7dad76e-36e3-4896-bab1-0406627b0ee7")]
            public virtual RepoItemInfo ButtonHayırInfo
            {
                get
                {
                    return _buttonhayırInfo;
                }
            }

            /// <summary>
            /// The Yeni item.
            /// </summary>
            [RepositoryItem("d46b37e0-1c37-48e0-a62e-b6d36f39a2fe")]
            public virtual Ranorex.Button Yeni
            {
                get
                {
                    return _yeniInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Yeni item info.
            /// </summary>
            [RepositoryItemInfo("d46b37e0-1c37-48e0-a62e-b6d36f39a2fe")]
            public virtual RepoItemInfo YeniInfo
            {
                get
                {
                    return _yeniInfo;
                }
            }

            /// <summary>
            /// The AlimSiparisiFisNo item.
            /// </summary>
            [RepositoryItem("5b3d6933-622e-495e-816f-31b3b5b33ae0")]
            public virtual Ranorex.Unknown AlimSiparisiFisNo
            {
                get
                {
                    return _alimsiparisifisnoInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The AlimSiparisiFisNo item info.
            /// </summary>
            [RepositoryItemInfo("5b3d6933-622e-495e-816f-31b3b5b33ae0")]
            public virtual RepoItemInfo AlimSiparisiFisNoInfo
            {
                get
                {
                    return _alimsiparisifisnoInfo;
                }
            }

            /// <summary>
            /// The BelgeNo item.
            /// </summary>
            [RepositoryItem("0f0ba7e4-ec7e-45cc-a368-62d7709f3067")]
            public virtual Ranorex.Unknown BelgeNo
            {
                get
                {
                    return _belgenoInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BelgeNo item info.
            /// </summary>
            [RepositoryItemInfo("0f0ba7e4-ec7e-45cc-a368-62d7709f3067")]
            public virtual RepoItemInfo BelgeNoInfo
            {
                get
                {
                    return _belgenoInfo;
                }
            }

            /// <summary>
            /// The CariHesap item.
            /// </summary>
            [RepositoryItem("72cb7f36-1c6f-427a-8373-cb51df793a9c")]
            public virtual Ranorex.Unknown CariHesap
            {
                get
                {
                    return _carihesapInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The CariHesap item info.
            /// </summary>
            [RepositoryItemInfo("72cb7f36-1c6f-427a-8373-cb51df793a9c")]
            public virtual RepoItemInfo CariHesapInfo
            {
                get
                {
                    return _carihesapInfo;
                }
            }

            /// <summary>
            /// The KullanilacakParaBirimiSatirlar item.
            /// </summary>
            [RepositoryItem("2b27f1a1-b3e4-4fb0-a823-5023a332077c")]
            public virtual Ranorex.Unknown KullanilacakParaBirimiSatirlar
            {
                get
                {
                    return _kullanilacakparabirimisatirlarInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The KullanilacakParaBirimiSatirlar item info.
            /// </summary>
            [RepositoryItemInfo("2b27f1a1-b3e4-4fb0-a823-5023a332077c")]
            public virtual RepoItemInfo KullanilacakParaBirimiSatirlarInfo
            {
                get
                {
                    return _kullanilacakparabirimisatirlarInfo;
                }
            }

            /// <summary>
            /// The IslemDovizTuru item.
            /// </summary>
            [RepositoryItem("3f767137-8d92-4bd9-aa6b-746034e07870")]
            public virtual Ranorex.Unknown IslemDovizTuru
            {
                get
                {
                    return _islemdovizturuInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The IslemDovizTuru item info.
            /// </summary>
            [RepositoryItemInfo("3f767137-8d92-4bd9-aa6b-746034e07870")]
            public virtual RepoItemInfo IslemDovizTuruInfo
            {
                get
                {
                    return _islemdovizturuInfo;
                }
            }

            /// <summary>
            /// The Yeni1 item.
            /// </summary>
            [RepositoryItem("86b39e30-9702-4a68-83a8-703e0bfb9ccc")]
            public virtual Ranorex.Button Yeni1
            {
                get
                {
                    return _yeni1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Yeni1 item info.
            /// </summary>
            [RepositoryItemInfo("86b39e30-9702-4a68-83a8-703e0bfb9ccc")]
            public virtual RepoItemInfo Yeni1Info
            {
                get
                {
                    return _yeni1Info;
                }
            }

            /// <summary>
            /// The Table item.
            /// </summary>
            [RepositoryItem("29f627e9-f194-40f7-ab7d-8f3bcedd921d")]
            public virtual Ranorex.Table Table
            {
                get
                {
                    return _tableInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Table item info.
            /// </summary>
            [RepositoryItemInfo("29f627e9-f194-40f7-ab7d-8f3bcedd921d")]
            public virtual RepoItemInfo TableInfo
            {
                get
                {
                    return _tableInfo;
                }
            }

            /// <summary>
            /// The KaydetVeKapat item.
            /// </summary>
            [RepositoryItem("032a3692-49d2-4009-b5ab-7a7d0f5bba4f")]
            public virtual Ranorex.Button KaydetVeKapat
            {
                get
                {
                    return _kaydetvekapatInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The KaydetVeKapat item info.
            /// </summary>
            [RepositoryItemInfo("032a3692-49d2-4009-b5ab-7a7d0f5bba4f")]
            public virtual RepoItemInfo KaydetVeKapatInfo
            {
                get
                {
                    return _kaydetvekapatInfo;
                }
            }

            /// <summary>
            /// The OnayıİptalEt item.
            /// </summary>
            [RepositoryItem("b661e5df-0faf-49fc-9a8c-a3ad3a29f5c2")]
            public virtual Ranorex.Button OnayıİptalEt
            {
                get
                {
                    return _onayıİptaletInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OnayıİptalEt item info.
            /// </summary>
            [RepositoryItemInfo("b661e5df-0faf-49fc-9a8c-a3ad3a29f5c2")]
            public virtual RepoItemInfo OnayıİptalEtInfo
            {
                get
                {
                    return _onayıİptaletInfo;
                }
            }
        }

        /// <summary>
        /// The PopupFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("838e4a8a-d1b6-4c7e-bd7d-9caae382a530")]
        public partial class PopupFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tamamInfo;

            /// <summary>
            /// Creates a new PopupForm  folder.
            /// </summary>
            public PopupFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PopupForm", "/form[@controlname='PopupForm']", parentFolder, 30000, null, true, "838e4a8a-d1b6-4c7e-bd7d-9caae382a530", "")
            {
                _tamamInfo = new RepoItemInfo(this, "Tamam", "?/?/container[@controlname='buttonsContainer']/?/?/button[@accessiblename='Tamam']", 30000, null, "517f4b79-0db1-4156-87d8-f13481476b1a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("838e4a8a-d1b6-4c7e-bd7d-9caae382a530")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("838e4a8a-d1b6-4c7e-bd7d-9caae382a530")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tamam item.
            /// </summary>
            [RepositoryItem("517f4b79-0db1-4156-87d8-f13481476b1a")]
            public virtual Ranorex.Button Tamam
            {
                get
                {
                    return _tamamInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Tamam item info.
            /// </summary>
            [RepositoryItemInfo("517f4b79-0db1-4156-87d8-f13481476b1a")]
            public virtual RepoItemInfo TamamInfo
            {
                get
                {
                    return _tamamInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
