///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CoralReefTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GirisYap recording.
    /// </summary>
    [TestModule("1216d236-0941-4eb6-bc0b-82a327fd643a", ModuleType.Recording, 1)]
    public partial class GirisYap : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CoralReefTestRepository repository.
        /// </summary>
        public static CoralReefTestRepository repo = CoralReefTestRepository.Instance;

        static GirisYap instance = new GirisYap();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GirisYap()
        {
            varKullaniciAdi = "admin";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GirisYap Instance
        {
            get { return instance; }
        }

#region Variables

        string _varKullaniciAdi;

        /// <summary>
        /// Gets or sets the value of variable varKullaniciAdi.
        /// </summary>
        [TestVariable("7dddff38-4be8-4fe9-8f19-755afd29f1b6")]
        public string varKullaniciAdi
        {
            get { return _varKullaniciAdi; }
            set { _varKullaniciAdi = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginScreen.txtUsername' at 66;15.", repo.LoginScreen.txtUsernameInfo, new RecordItemIndex(0));
            repo.LoginScreen.txtUsername.Click("66;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'LoginScreen.txtUsername'.", repo.LoginScreen.txtUsernameInfo, new RecordItemIndex(1));
            Keyboard.PrepareFocus(repo.LoginScreen.txtUsername);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varKullaniciAdi' with focus on 'LoginScreen.txtUsername'.", repo.LoginScreen.txtUsernameInfo, new RecordItemIndex(2));
            repo.LoginScreen.txtUsername.PressKeys(varKullaniciAdi);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginScreen.SİSTEMEBAĞLAN' at Center.", repo.LoginScreen.SİSTEMEBAĞLANInfo, new RecordItemIndex(3));
            repo.LoginScreen.SİSTEMEBAĞLAN.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
