///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CoralReefTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SatisSiparisi recording.
    /// </summary>
    [TestModule("0891341f-c7c8-40d7-b385-71dbae6ec49b", ModuleType.Recording, 1)]
    public partial class SatisSiparisi : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CoralReefTestRepository repository.
        /// </summary>
        public static CoralReefTestRepository repo = CoralReefTestRepository.Instance;

        static SatisSiparisi instance = new SatisSiparisi();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SatisSiparisi()
        {
            satisSiparisiFisNo = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SatisSiparisi Instance
        {
            get { return instance; }
        }

#region Variables

        string _satisSiparisiFisNo;

        /// <summary>
        /// Gets or sets the value of variable satisSiparisiFisNo.
        /// </summary>
        [TestVariable("f756f8e5-cd0a-4404-8a7c-769578c4dd58")]
        public string satisSiparisiFisNo
        {
            get { return _satisSiparisiFisNo; }
            set { _satisSiparisiFisNo = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SatisSiparisi.Yeni' at UpperCenter.", repo.SatisSiparisi.YeniInfo, new RecordItemIndex(0));
            repo.SatisSiparisi.Yeni.Click(Location.UpperCenter);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'ControlText' from item 'SatisSiparisiDetaylari.FisNo' and assigning its value to variable 'satisSiparisiFisNo'.", repo.SatisSiparisiDetaylari.FisNoInfo, new RecordItemIndex(1));
            satisSiparisiFisNo = repo.SatisSiparisiDetaylari.FisNo.Element.GetAttributeValueText("ControlText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", satisSiparisiFisNo, new RecordItemIndex(2));
            
            // Test
            Report.Log(ReportLevel.Info, "Section", "Test", new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SatisSiparisiDetaylari.CariHesap' at Center.", repo.SatisSiparisiDetaylari.CariHesapInfo, new RecordItemIndex(4));
            repo.SatisSiparisiDetaylari.CariHesap.Click();
            Delay.Milliseconds(0);
            
            clickToTableCellWithSearchValue(repo.CoralReef.TableInfo, "CH Kodu", "5");
            Delay.Milliseconds(0);
            
            // Yeni Kayıt
            Report.Log(ReportLevel.Info, "Section", "Yeni Kayıt", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SatisSiparisiDetaylari.Yeni' at Center.", repo.SatisSiparisiDetaylari.YeniInfo, new RecordItemIndex(7));
            repo.SatisSiparisiDetaylari.Yeni.Click();
            Delay.Milliseconds(0);
            
            writeToTableCell(repo.SatisSiparisiDetaylari.TableInfo, "Miktar", ValueConverter.ArgumentFromString<int>("rowIndex", "1"), "100");
            Delay.Milliseconds(0);
            
            // Stok Kartı Seçimi
            Report.Log(ReportLevel.Info, "Section", "Stok Kartı Seçimi", new RecordItemIndex(9));
            
            clickToTableCell(repo.SatisSiparisiDetaylari.TableInfo, "Stok Kartı", ValueConverter.ArgumentFromString<int>("rowIndex", "1"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'MAMUL01' with focus on 'CoralReef.StokKartiSearchBox'.", repo.CoralReef.StokKartiSearchBoxInfo, new RecordItemIndex(11));
            repo.CoralReef.StokKartiSearchBox.PressKeys("MAMUL01");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CoralReef.StokKartiSearchButton' at Center.", repo.CoralReef.StokKartiSearchButtonInfo, new RecordItemIndex(12));
            repo.CoralReef.StokKartiSearchButton.Click();
            Delay.Milliseconds(0);
            
            clickToTableCellWithSearchValue(repo.CoralReef.TableInfo, "Adı", "MAMUL01");
            Delay.Milliseconds(0);
            
            // Kaydet İşlemleri
            Report.Log(ReportLevel.Info, "Section", "Kaydet İşlemleri", new RecordItemIndex(14));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CoralReef1.Kaydet' at Center.", repo.CoralReef1.KaydetInfo, new RecordItemIndex(15));
            repo.CoralReef1.Kaydet.Click();
            Delay.Milliseconds(0);
            
            clickToTableCell(repo.SatisSiparisiDetaylari.TableInfo, "Seç", ValueConverter.ArgumentFromString<int>("rowIndex", "1"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SatisSiparisiDetaylari.UretimEmriOlustur' at Center.", repo.SatisSiparisiDetaylari.UretimEmriOlusturInfo, new RecordItemIndex(17));
            repo.SatisSiparisiDetaylari.UretimEmriOlustur.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PopupForm.Tamam' at Center.", repo.PopupForm.TamamInfo, new RecordItemIndex(18));
            repo.PopupForm.Tamam.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>'Üretim emrinde kullanılacak yarı mamüller içinde üretim emri oluşturulsun mu ?') on item 'CoralReef1.MessageLabel'.", repo.CoralReef1.MessageLabelInfo, new RecordItemIndex(19));
            Validate.AttributeContains(repo.CoralReef1.MessageLabelInfo, "Text", "Üretim emrinde kullanılacak yarı mamüller içinde üretim emri oluşturulsun mu ?");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CoralReef1.Evet' at Center.", repo.CoralReef1.EvetInfo, new RecordItemIndex(20));
            repo.CoralReef1.Evet.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>'Üretim emri veya üretim emirleri') on item 'CoralReef1.MessageLabel'.", repo.CoralReef1.MessageLabelInfo, new RecordItemIndex(21));
            Validate.AttributeContains(repo.CoralReef1.MessageLabelInfo, "Text", "Üretim emri veya üretim emirleri");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CoralReef1.ButtonHayır' at Center.", repo.CoralReef1.ButtonHayırInfo, new RecordItemIndex(22));
            repo.CoralReef1.ButtonHayır.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SatisSiparisiDetaylari.Kapat' at Center.", repo.SatisSiparisiDetaylari.KapatInfo, new RecordItemIndex(23));
            repo.SatisSiparisiDetaylari.Kapat.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
